//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comment_id { get; set; }
        public int account_id { get; set; }
        public int personal_report_id { get; set; }
        public string comment_content { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual PersonalReport PersonalReport { get; set; }
    }
}
