//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentReportDetail
    {
        public int department_report_detail_id { get; set; }
        public int department_report_id { get; set; }
        public int form_department_report_detail_id { get; set; }
        public string department_report_content { get; set; }
        public Nullable<int> comment_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual DepartmentReport DepartmentReport { get; set; }
        public virtual FormDepartmentReportDetail FormDepartmentReportDetail { get; set; }
    }
}
