//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int mapping_id { get; set; }
        public Nullable<int> department_report_detail_id { get; set; }
        public Nullable<int> personal_report_detail_id { get; set; }
    
        public virtual DepartmentReportDetail DepartmentReportDetail { get; set; }
        public virtual PersonalReportDetail PersonalReportDetail { get; set; }
    }
}
