//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public int account_id { get; set; }
        public string notification_content { get; set; }
        public Nullable<System.DateTime> notification_date { get; set; }
        public string status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
