//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalReportDetail
    {
        public int personal_report_detail_id { get; set; }
        public int personal_report_id { get; set; }
        public int form_personal_report_detail_id { get; set; }
        public string personal_report_content { get; set; }
        public Nullable<int> comment_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual FormPersonalReportDetail FormPersonalReportDetail { get; set; }
        public virtual PersonalReport PersonalReport { get; set; }
    }
}
