//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalReport()
        {
            this.Comments = new HashSet<Comment>();
            this.PersonalReportDetails = new HashSet<PersonalReportDetail>();
        }
    
        public int personal_report_id { get; set; }
        public int report_period_id { get; set; }
        public string file_path { get; set; }
        public string status { get; set; }
        public string account_id { get; set; }
        public Nullable<System.DateTime> date_report { get; set; }
        public string reporter { get; set; }
        public string user_code { get; set; }
        public string role_user { get; set; }
        public string user_department { get; set; }
        public string user_faculty { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalReportDetail> PersonalReportDetails { get; set; }
        public virtual ReportPeriod ReportPeriod { get; set; }
    }
}
