//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int profile_id { get; set; }
        public int account_id { get; set; }
        public string user_name { get; set; }
        public string department { get; set; }
        public string majors { get; set; }
        public string avatar { get; set; }
        public Nullable<int> faculty_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
