//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonthlyStatement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffReportDetail
    {
        public int staff_report_detail_id { get; set; }
        public int staff_report_id { get; set; }
        public int form_staff_report_detail_id { get; set; }
        public string staff_report_content { get; set; }
    
        public virtual FormStaffReportDetail FormStaffReportDetail { get; set; }
        public virtual StaffReport StaffReport { get; set; }
    }
}
